variables:
  PROD_BRANCH: "main"
  STAGING_BRANCH: "staging"

stages:
  - lint
  - build

linting:
  stage: lint
  image: python:3.12-bookworm
  script:
    - pip install -r requirements.txt
    - ruff check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  tags:
    - docker